plugins {
    id 'application'
}

dependencies {
    implementation project(':common')
    implementation project(':quadrant')
    implementation project(':ship')
    implementation project(':klingon')
}

tasks.withType(JavaExec).configureEach {
    enableAssertions = true
}

application {
    mainClass = 'QuadrantMap.Main'
}