plugins {
    id 'application'
}

dependencies {
    implementation project(':common')
    implementation project(':quadrant')
    implementation project(':QuadrantMap')
    implementation project(':ship')
    implementation project(':device')
    implementation project(':enterprise')
    implementation project(':galaxy')
    implementation project(':klingon')
}

tasks.withType(JavaExec).configureEach {
    enableAssertions = true
}

application {
    mainClass = 'Game.Main'
}

run {
    standardInput = System.in;
}