pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'mr-bradley-assignments'

include 'common'
include 'light'
include 'quadrant'
include 'galaxy'
include 'device'
include 'ship'
include 'enterprise'